PROJ_ROOT=../..
PROJ_DIR=appsSwingGui/SeidelTriag
TARGETDIR=Triangulation
JAVACOPT=-target 1.5 -source 1.5

SRCDIRS=.

LIBS = anja/geom anja/util anja/swinggui

WMLFILES:=$(wildcard *.wml)

WEBFILES:=$(wildcard *.gif) $(wildcard *.jpg) $(wildcard *.png) \
	$(wildcard pics/*.gif) $(wildcard pics/*.jpg) $(wildcard pics/*.png)

include $(PROJ_ROOT)/Make.Start
